version: "3"
services:
    nginx:
        ports:
            - "3000:80"
    node-docker-app:
        build:
            context: .
            args:
                - NODE_ENV=development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        env_file:
            - ./.env
        command: npm run dev

    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password